# Generated by Django 5.1.7 on 2025-06-25 14:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoZip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='zips/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
