# Generated by Django 5.1.7 on 2025-06-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivozip',
            name='zip_bytes',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arquivozip',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='zips/'),
        ),
    ]
