# Generated by Django 5.1.7 on 2025-06-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0002_arquivozip_zip_bytes_alter_arquivozip_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivozip',
            name='arquivo',
        ),
    ]
