# Generated by Django 5.1.7 on 2025-07-03 14:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0003_remove_arquivozip_arquivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do pacote', max_length=100)),
                ('credits', models.IntegerField(help_text='Quantidade de créditos')),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço em reais', max_digits=10)),
                ('bonus_credits', models.IntegerField(default=0, help_text='Créditos bônus')),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False, help_text='Marcar como mais popular')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pacote de Créditos',
                'verbose_name_plural': 'Pacotes de Créditos',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credits_amount', models.IntegerField(help_text='Quantidade de créditos a serem adicionados')),
                ('price', models.DecimalField(decimal_places=2, help_text='Valor em reais', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('CANCELLED', 'Cancelado'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=20)),
                ('pix_code', models.TextField(blank=True, help_text='Código PIX para pagamento', null=True)),
                ('pix_qr_code', models.TextField(blank=True, help_text='QR Code PIX em base64', null=True)),
                ('pix_expires_at', models.DateTimeField(blank=True, null=True)),
                ('payment_proof', models.TextField(blank=True, help_text='Comprovante de pagamento', null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de Pagamento',
                'verbose_name_plural': 'Pedidos de Pagamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Compra'), ('USAGE', 'Uso'), ('REFUND', 'Reembolso'), ('BONUS', 'Bônus')], max_length=20)),
                ('amount', models.IntegerField(help_text='Quantidade de créditos (positivo para compra, negativo para uso)')),
                ('balance_after', models.IntegerField(help_text='Saldo após a transação')),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('payment_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extract.paymentorder')),
            ],
            options={
                'verbose_name': 'Transação de Crédito',
                'verbose_name_plural': 'Transações de Créditos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, help_text='Saldo atual de créditos')),
                ('total_purchased', models.IntegerField(default=0, help_text='Total de créditos comprados')),
                ('total_used', models.IntegerField(default=0, help_text='Total de créditos utilizados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Créditos do Usuário',
                'verbose_name_plural': 'Créditos dos Usuários',
            },
        ),
    ]
