# Generated by Django 5.1.7 on 2025-07-25 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0005_alter_arquivozip_options_arquivozip_nome_arquivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('respondido', 'Respondido'), ('fechado', 'Fechado')], default='aberto', help_text='Status do ticket', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação do ticket')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização do ticket')),
                ('priority', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', help_text='Prioridade do ticket', max_length=20)),
                ('subject', models.CharField(help_text='Assunto do ticket', max_length=200)),
                ('response', models.TextField(blank=True, help_text='Resposta do suporte', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='support_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='extract.supportticket')),
            ],
        ),
    ]
