# Generated by Django 5.1.7 on 2025-07-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0006_supportticket_supportticketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='description',
            field=models.TextField(default='Descrição não informada', help_text='Descrição do problema'),
            preserve_default=False,
        ),
    ]
