# Generated by Django 5.1.7 on 2025-07-30 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0007_supportticket_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(help_text='ID da tarefa', max_length=100)),
                ('status', models.CharField(help_text='Status da tarefa', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação do status')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização do status')),
                ('result', models.TextField(blank=True, help_text='Resultado da tarefa (se aplicável)', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
