# Generated by Django 5.1.7 on 2025-08-19 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0008_taskstatusmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFileCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, help_text='Número de arquivos processados')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Data da última atualização do contador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_file_counts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contador de Arquivos Processados',
                'verbose_name_plural': 'Contadores de Arquivos Processados',
            },
        ),
        migrations.CreateModel(
            name='SettingsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(help_text='Campo alterado', max_length=50)),
                ('old_value', models.JSONField(help_text='Valor anterior')),
                ('new_value', models.JSONField(help_text='Novo valor')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_changes_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Configurações',
                'verbose_name_plural': 'Históricos de Configurações',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications', models.JSONField(default=dict, help_text='Configurações de notificações')),
                ('preferences', models.JSONField(default=dict, help_text='Preferências do usuário')),
                ('security', models.JSONField(default=dict, help_text='Configurações de segurança')),
                ('api_key', models.CharField(blank=True, help_text='Chave da API do usuário', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configurações do Usuário',
                'verbose_name_plural': 'Configurações dos Usuários',
            },
        ),
    ]
