# Generated by Django 5.1.7 on 2025-08-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0010_profilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticketattachment',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
