# Generated by Django 5.1.7 on 2025-09-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0011_supportticketattachment_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='email',
            field=models.EmailField(blank=True, help_text='Email para resposta do ticket', max_length=254, null=True),
        ),
    ]
