# Generated by Django 5.1.7 on 2025-09-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0012_supportticket_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesProccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('proccess_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
